export const ADD = 'ADD';
export const SUB = 'SUB';
export const ADD_TOTAL_PRICE = 'ADD_TOTAL_PRICE';
export const SUB_TOTAL_PRICE = 'SUB_TOTAL_PRICE';
export const SET_INGREDIENTS = 'GET_INGREDIENTS';
export const ERROR_INGREDIENTS = 'ERROR_INGREDIENTS';

export const POST_SUCESS = 'POST_SUCESS';
export const POST_FAIL = 'POST_FAIL';

export const CHANGE_LOADING_VAL = 'CHANGE_LOADING_VAL';
export const CLEAR_RESPONSE_STATUS = 'CLEAR_RESPONSE_STATUS';

export const FETCHING_ORDERS = 'FETCHING_ORDERS';
export const FETCHING_ORDERS_FAIL = 'FETCHING_ORDERS_FAIL';